services:
  cleaningservice:
    build:
      context: ./cleaningService
    image: cleaningservice:local
    container_name: cleaning_service
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - appnet

  restaurantservice:
    build:
      context: ./restaurantService
    image: restaurantservice:local
    container_name: restaurant_service
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5001:5000" # map host 5001 -> container 5000
    networks:
      - appnet

  guestservice:
    build:
      context: ./Guestservice
      dockerfile: DockerFile
    image: guestservice:local
    container_name: guest_service
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5002:5000"
    networks:
      - appnet

  reservationservice:
    build:
      context: ./resevationService
      dockerfile: dockerfile
    image: reservationservice:local
    container_name: reservation_service
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5003:5000"
    networks:
      - appnet

  roomschedulingservice:
    build:
      context: ./roomSchedulingService
      dockerfile: dockerfile
    image: roomschedulingservice:local
    container_name: roomscheduling_service
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5004:5000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
